<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>fclang</string>
  </array>
  <key>name</key>
  <string>FreakC</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>^::.*$|^h\[\].*$</string>
      <key>name</key>
      <string>comment.line</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(?&#60;=(function\[\] ))([A-Za-z_])\w+|(?&#60;=(label\[\] ))([A-Za-z_])\w+|</string>
      <key>name</key>
      <string>entity.name.function</string>
    </dict>
    <dict>
      <key>match</key>
      <string>([A-Za-z])\w+(?=\[\.\.\])|([A-Za-z])\w+(?=\[\:\:\])|(?&#60;=(call\[\] ))([A-Za-z_])\w+|(?&#60;=(^))([a-zA-Z_])+(?=(\.([A-Za-z_]+)\[\.\.\]))</string>
      <key>name</key>
      <string>support.function</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(%~1)+(?=(.[A-Za-z_])+)</string>
      <key>name</key>
      <string>variable.language</string>
    </dict>
    <dict>
      <key>match</key>
      <string>%%%%~([0-9])+|%%%~([0-9])+|%%~([0-9])+|%~([0-9])+</string>
      <key>name</key>
      <string>variable.parameter.function</string>
    </dict>
    <dict>
      <key>match</key>
      <string>=|\+|-|\*|/|\+\+|--</string>
      <key>name</key>
      <string>keyword.operator</string>
    </dict>
    <dict>
      <key>match</key>
      <string>([A-Za-z])\w+(?=\[\])</string>
      <key>name</key>
      <string>support.constant</string>
    </dict>
    <dict>
      <key>match</key>
      <string>".*"</string>
      <key>name</key>
      <string>string.quoted.double</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.fclang</string>
  <key>uuid</key>
  <string>6f5f460e-5ab0-4ce2-8cb7-0cafea6c46c9</string>
</dict>
</plist>