<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>fclang</string>
  </array>
  <key>name</key>
  <string>FreakC</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>function|endfunc|uprint|print|if_not_el|if_not_defined|if_not_exist|if_not|if_defined|if_exist|if_el|if|elif|EQU|LEQ|LSS|GEQ|GTR|NEQ|while|endwhile|repeat|until|\=\=|\+\+|\-\-|el\[\]</string>
      <key>name</key>
      <string>keyword.control</string>
    </dict>
    <dict>
      <key>match</key>
      <string>gen_lib_func|import|eq|var|cnd|inp|label|float|define|goto|call|lcall|end|deny</string>
      <key>name</key>
      <string>support.constant</string>
    </dict>
    <dict>
      <key>match</key>
      <string>arr_max|arr_min|arr_sum|arr_join|arr_indexOf|arr_length|enb_delay|sum|max|min|abs|odd|even|pow|factorial|fib_seq|fib|string_indexOf|string_endswith|string_startswith|string_trim|string_chr|string_length|string_upper|string_lower|reverse_string|ps|curl|key|clrscr|change_mode|change_color|insert|change_title|stop|hello_world|ipinf|sysinf|ping|scan_files|scan_strs|scan_str|scan_dir|loop|wait|ls|change_date|change_time|see_date|see_time|RestartSystem|ShutdownSystem|inf_loop|quit|open|copy|mov|fnd|fncstr|rename|read_file|remove_dir|del|change_dir|create_dir|local|endloc|drive</string>
      <key>name</key>
      <string>entity.name.function</string>
    </dict>
    <dict>
      <key>match</key>
      <string>".*"</string>
      <key>name</key>
      <string>string.quoted.double</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.fclang</string>
  <key>uuid</key>
  <string>6f5f460e-5ab0-4ce2-8cb7-0cafea6c46c9</string>
</dict>
</plist>