<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>fclang</string>
  </array>
  <key>name</key>
  <string>FreakC</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>ProduceTrash|EndTrash|SwearLine|Swear|DoIfTap|DoIfNotTap|DoIfFalse|DoIfDefined|DoIfExist|DoIfNotExist|DoIfNotDefined|DoIf|OrNot|EQU|LEQ|LSS|GEQ|GTR|NEQ|OddOrEven|TryMeHoe|TryMeBtch|SquareMyBois|WhileSuck|EndSuck|RepeatSuck|UntilStale|CubeMyBois|FuckUpLess|FuckUp|\:|\=\=|\+\+|\-\-|</string>
      <key>name</key>
      <string>keyword.control</string>
    </dict>
    <dict>
      <key>match</key>
      <string>Fuck|PoopInt|PoopString|PoopInput|PoopFnc|PoopFloat|Jelly|EatFnc|GrabFnc|LickFnc|Shit|Puke|Cum|Piss</string>
      <key>name</key>
      <string>support.constant</string>
    </dict>
    <dict>
      <key>match</key>
      <string>fnc|meme|str|typ|DisableCoolStuff\[fnc\]|EnableCoolStuff\[fnc\]|CloseHouse\[fnc\]|OpenHouse\[fnc\]|Cancer\[fnc\]|\[ecmt\]|\[cmt\]|FuckUnicode\[fnc\]</string>
      <key>name</key>
      <string>variable.parameter</string>
    </dict>
    <dict>
      <key>match</key>
      <string>SummonLegend|DumbCousin|TapSomeSht|Forget|ChangeSize|ChangeColor|InsertShits|ChangeName|GotoToilet|Patrick|Dani|Thicc|SpongeBob|HiM8|AreYaWinningSon|ILoveYou|GrabMeADrink|HelloWorld|HackMyIP|MyDirtyInfo|HackTheNet|ScanDir|ScanDiaries|ScanLetters|ScanOrgans|LoopStuffs|WaitForBus|MyMemory|BuyClock|BuyCalender|SeeDate|SeeTime|RestartSystem|ShutdownSystem|Loop|Die|PlayFile|CopyFile|MoveFile|FindTrash|FindShits|RenameFile|StealDiary|TrashDir|Trash|EatDir|PukeDir|EatDrive|</string>
      <key>name</key>
      <string>entity.name.function</string>
    </dict>
    <dict>
      <key>match</key>
      <string>Java|JSON|CoolHackerMan|HackLikeABoss</string>
      <key>name</key>
      <string>storage.type</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\s[0-9]+|\%|</string>
      <key>name</key>
      <string>constant.numeric</string>
    </dict>
    <dict>
		<key>match</key>
		<string>".*"</string>
		<key>name</key>
		<string>string.quoted.double</string>
	</dict>
  </array>
  <key>scopeName</key>
  <string>source.fclang</string>
  <key>uuid</key>
  <string>6f5f460e-5ab0-4ce2-8cb7-0cafea6c46c9</string>
</dict>
</plist>